"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m57jp+3cu1=nx=s_+hll8&syf^py=7hkk5wz^sn3ltljrlqpyu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'api_class_view',
    'generic_view_api',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'

# These are optional -- if they're set as environment variables they won't
# need to be set here as well

EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'


"""Previous Used mail setups services"""
# AWS_ACCESS_KEY_ID = "AKIAIF7HM32FWZ35K2CA"
# AWS_SECRET_ACCESS_KEY = "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"
AWS_ACCESS_KEY_ID="AKIAVQQCVU6UWRR5QQGT "
AWS_SECRET_ACCESS_KEY="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"
AWS_DEFAULT_REGION="ap-south-1"



EMAIL_HOST = "email-smtp.ap-south-1.amazonaws.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "AKIAVQQCVU6UYG45R5OV"
EMAIL_HOST_PASSWORD = "BKXOiM3Tk1m9HLUaOlXtZg6U9jbAakMNayVZol+TI1vz"
EMAIL_USE_TLS = True



# Additionally, if you are not using the default AWS region of us-east-1,
# you need to specify a region, like so:
# EMAIL_HOST = ""
# AWS_SES_REGION_NAME = 'ap-south-1'
# AWS_SES_REGION_ENDPOINT = 'email-smtp.ap-south-1.amazonaws.com '


# https://www.mindbowser.com/sending-email-templates-using-amazon-ses-with-django-rest-framework/


"""

from django.core.mail import send_mail

send_mail(
    'Subject here',
    'sdfdsf is the message.',
    'support@myparkplus.com',
    ['vikas.pal@myparkplus.com']
)

"""